baseurl = ""
title = "SuperWriter"
theme = "SuperWriter"
languageCode = "en-uk"
copyright = ""
googleAnalytics = ""

[Privacy]

[Privacy.disqus]
    disable = true

[Privacy.googleAnalytics]
    anonymizeIP = false
    respectDoNotTrack = false
    useSessionStorage = false

[Author]
    name = ""
    profile = ""

[Taxonomies]
    category = "categories"
	series = "series"
    tag = "tags"

[Params]
    mainSections = ["posts"]
    intro = true
    headline = "SuperWriter Theme"
    description = "SuperWriter Theme"
    github = ""
    gitlab = ""
	facebook = ""
    linkedin = ""
    twitter = ""
    stackoverflow = ""
	quora = ""
    email = ""
    opengraph = true
    shareTwitter = true
    shareFacebook = true
    shareGooglePlus = true
    shareLinkedIn = true
    dateFormat = "Mon, 2 Jan 2006"
    readingTime = true
    readingTimeText = "Estimated reading time:"
	enableRobotsTXT = true
	UtterancesRepo = ""
    UtterancesIssueTerm = "title"
    UtterancesTheme = "github-light"

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Projects"
    url = "/pages/project/"
    weight = 2

[[menu.main]]
    name = "Contact"
    url = "/pages/contact/"
    weight = 3

[[menu.main]]
    name = "About"
    url = "/pages/about/"
    weight = 4
